version: '3.2'

services:
  jenkins_with_speedtest:
    build: .
    restart: always
    ports:
      - '8081:8080'
      - '50001:50000'
    environment:
      - JAVA_OPTS='-Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8'
    volumes:
      - ./volumes/var/jenkins_home:/var/jenkins_home
